/**
 * Central default naming for user-drawn routes & stations.
 *
 * Contract (do not bypass this module for display / auto names):
 * - User line display name: 路線rN (sequential label; N independent of internal route_id)
 * - User station display name: 站sN (sequential label; N independent of internal station_id)
 * - Legacy names (子路線 r1, 站 s1, raw ids, etc.) are migrated on load
 */
import { t } from "../i18n/i18n.js";

export function formatDefaultLineName(routeId) {
  if (typeof routeId !== "string" || !routeId) return "";
  return t("routeModel.lineDefault", { id: routeId });
}

export function formatDefaultStationName(labelId) {
  if (typeof labelId !== "string" || !labelId) return "";
  return t("routeModel.stationDefault", { id: labelId });
}

const LINE_NAME_PREFIX = /^(?:子路線|Sub-route|路線|Line)\s*(.+)$/iu;

/** Extract id key from legacy/auto line name patterns, or null. */
export function parseLegacyLineNameKey(name) {
  if (typeof name !== "string") return null;
  const trimmed = name.trim();
  if (!trimmed) return null;
  const prefixed = trimmed.match(LINE_NAME_PREFIX);
  if (prefixed) return prefixed[1].trim();
  return null;
}

/** Parse display label number from 路線r1 / Line r1. Returns integer or null. */
export function parseDefaultLineLabelFromName(name) {
  const key = parseLegacyLineNameKey(name);
  if (!key) return null;
  const m = key.match(/^r(\d+)$/i);
  if (!m) return null;
  const num = parseInt(m[1], 10);
  return Number.isFinite(num) ? num : null;
}

function lineLabelKey(labelNumber) {
  return `r${labelNumber}`;
}

/** True when `name` should be replaced by the default 路線rN label. */
export function isAutoGeneratedLineName(name, routeId, lineLabel) {
  if (typeof lineLabel === "number" && Number.isFinite(lineLabel)) {
    const labelKey = lineLabelKey(lineLabel);
    if (typeof name !== "string" || !name.trim()) return true;
    if (name.trim() === labelKey) return true;
    if (name === formatDefaultLineName(labelKey)) return true;
    if (name === t("routeModel.subRouteDefault", { id: labelKey })) return true;
    const key = parseLegacyLineNameKey(name);
    if (key === labelKey) return true;
    if (parseDefaultLineLabelFromName(name) === lineLabel) return true;
    return false;
  }
  if (typeof routeId !== "string" || !routeId) return true;
  if (typeof name !== "string" || !name.trim()) return true;
  if (name.trim() === routeId) return true;
  if (name === formatDefaultLineName(routeId)) return true;
  if (name === t("routeModel.subRouteDefault", { id: routeId })) return true;
  if (name === t("routeList.lineFallback", { id: routeId })) return true;
  if (parseDefaultLineLabelFromName(name) != null) return true;
  const key = parseLegacyLineNameKey(name);
  return key === routeId;
}

export function resolveLineDisplayName(storedName, routeId, lineLabel) {
  if (typeof lineLabel === "number" && Number.isFinite(lineLabel)) {
    return isAutoGeneratedLineName(storedName, routeId, lineLabel)
      ? formatDefaultLineName(lineLabelKey(lineLabel))
      : String(storedName).trim();
  }
  return isAutoGeneratedLineName(storedName, routeId)
    ? formatDefaultLineName(routeId)
    : String(storedName).trim();
}

export function resolveLineDisplayNameFromProps(props) {
  if (!props || typeof props !== "object") return "";
  return resolveLineDisplayName(props.name, props.route_id, props.user_default_line_label);
}

const STATION_LABEL_FROM_NAME = /^(?:站|車站|Station)\s*(s\d+)$/iu;

/** Parse display label number from 站s1 / Station s1 / 車站s2. Returns integer or null. */
export function parseDefaultStationLabelFromName(name) {
  if (typeof name !== "string") return null;
  const m = name.trim().match(STATION_LABEL_FROM_NAME);
  if (!m) return null;
  const num = parseInt(m[1].slice(1), 10);
  return Number.isFinite(num) ? num : null;
}

export function isLegacyStationName(name, stationId) {
  if (typeof name !== "string" || !name.trim()) return true;
  if (name.trim() === stationId) return true;
  if (parseDefaultStationLabelFromName(name) != null) return true;
  return false;
}

export function resolveStationDisplayName(props) {
  if (!props || typeof props !== "object") return "";
  const stationId = props.station_id;
  if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
    return formatDefaultStationName(`s${props.user_default_label}`);
  }
  const name = props.name;
  if (typeof name === "string" && name.trim() && !isLegacyStationName(name, stationId)) {
    return name.trim();
  }
  const fromName = parseDefaultStationLabelFromName(name);
  if (fromName != null) return formatDefaultStationName(`s${fromName}`);
  if (typeof stationId === "string" && stationId) return formatDefaultStationName(stationId);
  return "";
}

export function firstAvailableLabelNumber(usedSet) {
  let n = 1;
  while (usedSet.has(n)) n += 1;
  return n;
}

export function collectUsedDefaultStationLabelNumbers(stations, isUserStation) {
  const used = new Set();
  if (!Array.isArray(stations)) return used;
  for (const f of stations) {
    if (typeof isUserStation === "function" && !isUserStation(f)) continue;
    const props = f?.properties;
    if (!props) continue;
    if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
      used.add(props.user_default_label);
      continue;
    }
    const fromName = parseDefaultStationLabelFromName(props.name);
    if (fromName != null) used.add(fromName);
  }
  return used;
}

export function nextDefaultStationLabelNumber(stations, isUserStation) {
  return firstAvailableLabelNumber(collectUsedDefaultStationLabelNumbers(stations, isUserStation));
}

function collectUserLineGroups(routes, isUserRoute) {
  const byGroup = new Map();
  if (!Array.isArray(routes)) return byGroup;
  for (const f of routes) {
    if (typeof isUserRoute === "function" && !isUserRoute(f)) continue;
    const gid = f?.properties?.group_id;
    if (typeof gid !== "string") continue;
    if (!byGroup.has(gid)) byGroup.set(gid, []);
    byGroup.get(gid).push(f);
  }
  return byGroup;
}

function headRouteInGroup(groupRoutes) {
  return [...groupRoutes].sort(
    (a, b) => routeIdSortKey(a.properties?.route_id) - routeIdSortKey(b.properties?.route_id)
  )[0];
}

/** Line groups that use auto default names (路線rN), one label per group_id. */
export function collectUsedDefaultLineLabelNumbers(routes, isUserRoute) {
  const used = new Set();
  for (const groupRoutes of collectUserLineGroups(routes, isUserRoute).values()) {
    const head = headRouteInGroup(groupRoutes);
    const props = head?.properties;
    if (!props) continue;
    if (!isAutoGeneratedLineName(props.name, props.route_id, props.user_default_line_label)) continue;
    if (typeof props.user_default_line_label === "number" && Number.isFinite(props.user_default_line_label)) {
      used.add(props.user_default_line_label);
      continue;
    }
    const fromName = parseDefaultLineLabelFromName(props.name);
    if (fromName != null) used.add(fromName);
  }
  return used;
}

export function nextDefaultLineLabelNumber(routes, isUserRoute) {
  return firstAvailableLabelNumber(collectUsedDefaultLineLabelNumbers(routes, isUserRoute));
}

/** Assign the next sequential default line label + display name for a new user line. */
export function allocateDefaultLineLabel(routes, isUserRoute) {
  const label = nextDefaultLineLabelNumber(routes, isUserRoute);
  return {
    user_default_line_label: label,
    name: formatDefaultLineName(lineLabelKey(label)),
  };
}

/** Assign the next sequential default station label + display name. */
export function allocateDefaultStationLabel(stations, isUserStation) {
  const label = nextDefaultStationLabelNumber(stations, isUserStation);
  return {
    user_default_label: label,
    name: formatDefaultStationName(`s${label}`),
  };
}

/** Run line + station default-name normalization (mutates feature arrays). */
export function normalizeAllUserDefaultNames(routes, stations, isUserRoute, isUserStation) {
  normalizeUserRouteNamesInPlace(routes, isUserRoute);
  normalizeUserStationNamesInPlace(stations, isUserStation);
}

/** Whether renaming clears the stored default line label (custom name). */
export function shouldClearLineLabelOnRename(nextName, routeId, lineLabel) {
  return !isAutoGeneratedLineName(nextName, routeId, lineLabel);
}

/** Whether renaming clears the stored default station label (custom name). */
export function shouldClearStationLabelOnRename(nextName, stationId) {
  return !isLegacyStationName(nextName, stationId) && parseDefaultStationLabelFromName(nextName) == null;
}

function routeIdSortKey(routeId) {
  const m = typeof routeId === "string" ? routeId.match(/^r(\d+)$/) : null;
  return m ? parseInt(m[1], 10) : Number.MAX_SAFE_INTEGER;
}

/**
 * Normalize stored user route names and sync each line (group) to one display name.
 * @param {object[]} routes - route features (mutated)
 * @param {(feature: object) => boolean} isUserRoute
 */
export function normalizeUserRouteNamesInPlace(routes, isUserRoute) {
  if (!Array.isArray(routes)) return;
  const byGroup = collectUserLineGroups(routes, isUserRoute);
  const used = collectUsedDefaultLineLabelNumbers(routes, isUserRoute);

  for (const groupRoutes of byGroup.values()) {
    const head = headRouteInGroup(groupRoutes);
    const props = head?.properties;
    if (!props) continue;

    if (!isAutoGeneratedLineName(props.name, props.route_id, props.user_default_line_label)) {
      for (const r of groupRoutes) {
        delete r.properties.user_default_line_label;
      }
      continue;
    }

    let labelNumber = props.user_default_line_label;
    if (!Number.isFinite(labelNumber)) {
      labelNumber = parseDefaultLineLabelFromName(props.name);
    }
    if (!Number.isFinite(labelNumber)) {
      labelNumber = firstAvailableLabelNumber(used);
    }
    used.add(labelNumber);

    const display = formatDefaultLineName(lineLabelKey(labelNumber));
    for (const r of groupRoutes) {
      r.properties.user_default_line_label = labelNumber;
      r.properties.name = display;
    }
  }
}

/**
 * Normalize user station default names (站s1, 站s2, …).
 * @param {object[]} stations - station features (mutated)
 * @param {(feature: object) => boolean} isUserStation
 */
export function normalizeUserStationNamesInPlace(stations, isUserStation) {
  if (!Array.isArray(stations)) return;
  const used = collectUsedDefaultStationLabelNumbers(stations, isUserStation);

  for (const f of stations) {
    if (typeof isUserStation === "function" && !isUserStation(f)) continue;
    const props = f?.properties;
    const sid = props?.station_id;
    if (!props || typeof sid !== "string") continue;

    const labelFromName = parseDefaultStationLabelFromName(props.name);
    if (labelFromName != null && !isLegacyStationName(props.name, sid)) {
      props.user_default_label = labelFromName;
      props.name = formatDefaultStationName(`s${labelFromName}`);
      used.add(labelFromName);
      continue;
    }

    if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
      props.name = formatDefaultStationName(`s${props.user_default_label}`);
      used.add(props.user_default_label);
      continue;
    }

    if (!isLegacyStationName(props.name, sid)) continue;

    const labelNumber = firstAvailableLabelNumber(used);
    used.add(labelNumber);
    props.user_default_label = labelNumber;
    props.name = formatDefaultStationName(`s${labelNumber}`);
  }
}
