/**
 * Central default naming for user-drawn routes & stations.
 *
 * Contract (do not bypass this module for display / auto names):
 * - User line display name: 路線rN (sequential label; N independent of internal subroute_id)
 * - User station display name: 站sN (sequential label; N independent of internal station_id)
 * - Legacy names (子路線 r1, 站 s1, raw ids, etc.) are migrated on load
 */
import { t } from "../i18n/i18n.js";

export function formatDefaultRouteName(subrouteId) {
  if (typeof subrouteId !== "string" || !subrouteId) return "";
  return t("routeModel.lineDefault", { id: subrouteId });
}

export function formatDefaultStationName(labelId) {
  if (typeof labelId !== "string" || !labelId) return "";
  return t("routeModel.stationDefault", { id: labelId });
}

const LINE_NAME_PREFIX = /^(?:子路線|Sub-route|路線|Line)\s*(.+)$/iu;

/** Extract id key from legacy/auto line name patterns, or null. */
export function parseLegacyRouteNameKey(name) {
  if (typeof name !== "string") return null;
  const trimmed = name.trim();
  if (!trimmed) return null;
  const prefixed = trimmed.match(LINE_NAME_PREFIX);
  if (prefixed) return prefixed[1].trim();
  return null;
}

/** Parse display label number from 路線r1 / Line r1. Returns integer or null. */
export function parseDefaultRouteLabelFromName(name) {
  const key = parseLegacyRouteNameKey(name);
  if (!key) return null;
  const m = key.match(/^r(\d+)$/i);
  if (!m) return null;
  const num = parseInt(m[1], 10);
  return Number.isFinite(num) ? num : null;
}

function routeLabelKey(labelNumber) {
  return `r${labelNumber}`;
}

/** True when `name` should be replaced by the default 路線rN label. */
export function isAutoGeneratedRouteName(name, subrouteId, routeLabel) {
  if (typeof routeLabel === "number" && Number.isFinite(routeLabel)) {
    const labelKey = routeLabelKey(routeLabel);
    if (typeof name !== "string" || !name.trim()) return true;
    if (name.trim() === labelKey) return true;
    if (name === formatDefaultRouteName(labelKey)) return true;
    if (name === t("routeModel.subRouteDefault", { id: labelKey })) return true;
    const key = parseLegacyRouteNameKey(name);
    if (key === labelKey) return true;
    if (parseDefaultRouteLabelFromName(name) === routeLabel) return true;
    return false;
  }
  if (typeof subrouteId !== "string" || !subrouteId) return true;
  if (typeof name !== "string" || !name.trim()) return true;
  if (name.trim() === subrouteId) return true;
  if (name === formatDefaultRouteName(subrouteId)) return true;
  if (name === t("routeModel.subRouteDefault", { id: subrouteId })) return true;
  if (name === t("routeList.lineFallback", { id: subrouteId })) return true;
  if (parseDefaultRouteLabelFromName(name) != null) return true;
  const key = parseLegacyRouteNameKey(name);
  return key === subrouteId;
}

export function resolveRouteDisplayName(storedName, subrouteId, routeLabel) {
  if (typeof routeLabel === "number" && Number.isFinite(routeLabel)) {
    return isAutoGeneratedRouteName(storedName, subrouteId, routeLabel)
      ? formatDefaultRouteName(routeLabelKey(routeLabel))
      : String(storedName).trim();
  }
  return isAutoGeneratedRouteName(storedName, subrouteId)
    ? formatDefaultRouteName(subrouteId)
    : String(storedName).trim();
}

export function resolveRouteDisplayNameFromProps(props) {
  if (!props || typeof props !== "object") return "";
  return resolveRouteDisplayName(props.name, props.subroute_id, props.user_default_route_label);
}

const STATION_LABEL_FROM_NAME = /^(?:站|車站|Station)\s*(s\d+)$/iu;

/** Parse display label number from 站s1 / Station s1 / 車站s2. Returns integer or null. */
export function parseDefaultStationLabelFromName(name) {
  if (typeof name !== "string") return null;
  const m = name.trim().match(STATION_LABEL_FROM_NAME);
  if (!m) return null;
  const num = parseInt(m[1].slice(1), 10);
  return Number.isFinite(num) ? num : null;
}

export function isLegacyStationName(name, stationId) {
  if (typeof name !== "string" || !name.trim()) return true;
  if (name.trim() === stationId) return true;
  if (parseDefaultStationLabelFromName(name) != null) return true;
  return false;
}

export function resolveStationDisplayName(props) {
  if (!props || typeof props !== "object") return "";
  const stationId = props.station_id;
  if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
    return formatDefaultStationName(`s${props.user_default_label}`);
  }
  const name = props.name;
  if (typeof name === "string" && name.trim() && !isLegacyStationName(name, stationId)) {
    return name.trim();
  }
  const fromName = parseDefaultStationLabelFromName(name);
  if (fromName != null) return formatDefaultStationName(`s${fromName}`);
  if (typeof stationId === "string" && stationId) return formatDefaultStationName(stationId);
  return "";
}

export function firstAvailableLabelNumber(usedSet) {
  let n = 1;
  while (usedSet.has(n)) n += 1;
  return n;
}

export function collectUsedDefaultStationLabelNumbers(stations, isUserStation) {
  const used = new Set();
  if (!Array.isArray(stations)) return used;
  for (const f of stations) {
    if (typeof isUserStation === "function" && !isUserStation(f)) continue;
    const props = f?.properties;
    if (!props) continue;
    if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
      used.add(props.user_default_label);
      continue;
    }
    const fromName = parseDefaultStationLabelFromName(props.name);
    if (fromName != null) used.add(fromName);
  }
  return used;
}

export function nextDefaultStationLabelNumber(stations, isUserStation) {
  return firstAvailableLabelNumber(collectUsedDefaultStationLabelNumbers(stations, isUserStation));
}

function collectUserRoutes(routes, isUserRoute) {
  const byRoute = new Map();
  if (!Array.isArray(routes)) return byRoute;
  for (const f of routes) {
    if (typeof isUserRoute === "function" && !isUserRoute(f)) continue;
    const routeId = f?.properties?.route_id;
    if (typeof routeId !== "string") continue;
    if (!byRoute.has(routeId)) byRoute.set(routeId, []);
    byRoute.get(routeId).push(f);
  }
  return byRoute;
}

function headSubrouteInRoute(routeSubroutes) {
  return [...routeSubroutes].sort(
    (a, b) => subrouteIdSortKey(a.properties?.subroute_id) - subrouteIdSortKey(b.properties?.subroute_id)
  )[0];
}

/** Routes that use auto default names (路線rN), one label per route_id. */
export function collectUsedDefaultRouteLabelNumbers(routes, isUserRoute) {
  const used = new Set();
  for (const routeSubroutes of collectUserRoutes(routes, isUserRoute).values()) {
    const head = headSubrouteInRoute(routeSubroutes);
    const props = head?.properties;
    if (!props) continue;
    if (!isAutoGeneratedRouteName(props.name, props.subroute_id, props.user_default_route_label)) continue;
    if (typeof props.user_default_route_label === "number" && Number.isFinite(props.user_default_route_label)) {
      used.add(props.user_default_route_label);
      continue;
    }
    const fromName = parseDefaultRouteLabelFromName(props.name);
    if (fromName != null) used.add(fromName);
  }
  return used;
}

export function nextDefaultRouteLabelNumber(routes, isUserRoute) {
  return firstAvailableLabelNumber(collectUsedDefaultRouteLabelNumbers(routes, isUserRoute));
}

/** Assign the next sequential default line label + display name for a new user line. */
export function allocateDefaultRouteLabel(routes, isUserRoute) {
  const label = nextDefaultRouteLabelNumber(routes, isUserRoute);
  return {
    user_default_route_label: label,
    name: formatDefaultRouteName(routeLabelKey(label)),
  };
}

/** Assign the next sequential default station label + display name. */
export function allocateDefaultStationLabel(stations, isUserStation) {
  const label = nextDefaultStationLabelNumber(stations, isUserStation);
  return {
    user_default_label: label,
    name: formatDefaultStationName(`s${label}`),
  };
}

/** Run line + station default-name normalization (mutates feature arrays). */
export function normalizeAllUserDefaultNames(routes, stations, isUserRoute, isUserStation) {
  normalizeUserRouteNamesInPlace(routes, isUserRoute);
  normalizeUserStationNamesInPlace(stations, isUserStation);
}

/** Whether renaming clears the stored default line label (custom name). */
export function shouldClearRouteLabelOnRename(nextName, subrouteId, routeLabel) {
  return !isAutoGeneratedRouteName(nextName, subrouteId, routeLabel);
}

/** Whether renaming clears the stored default station label (custom name). */
export function shouldClearStationLabelOnRename(nextName, stationId) {
  return !isLegacyStationName(nextName, stationId) && parseDefaultStationLabelFromName(nextName) == null;
}

function subrouteIdSortKey(subrouteId) {
  const m = typeof subrouteId === "string" ? subrouteId.match(/^r(\d+)$/) : null;
  return m ? parseInt(m[1], 10) : Number.MAX_SAFE_INTEGER;
}

/**
 * Normalize stored user route names and sync each route to one display name.
 * @param {object[]} routes - route features (mutated)
 * @param {(feature: object) => boolean} isUserRoute
 */
export function normalizeUserRouteNamesInPlace(routes, isUserRoute) {
  if (!Array.isArray(routes)) return;
  const byRoute = collectUserRoutes(routes, isUserRoute);
  const used = new Set();

  for (const routeSubroutes of byRoute.values()) {
    const head = headSubrouteInRoute(routeSubroutes);
    const props = head?.properties;
    if (!props) continue;

    if (!isAutoGeneratedRouteName(props.name, props.subroute_id, props.user_default_route_label)) {
      for (const r of routeSubroutes) {
        delete r.properties.user_default_route_label;
      }
      continue;
    }

    let labelNumber = props.user_default_route_label;
    if (!Number.isFinite(labelNumber)) {
      labelNumber = parseDefaultRouteLabelFromName(props.name);
    }
    if (!Number.isFinite(labelNumber) || used.has(labelNumber)) {
      labelNumber = firstAvailableLabelNumber(used);
    }
    used.add(labelNumber);

    const display = formatDefaultRouteName(routeLabelKey(labelNumber));
    for (const r of routeSubroutes) {
      r.properties.user_default_route_label = labelNumber;
      r.properties.name = display;
    }
  }
}

/**
 * Normalize user station default names (站s1, 站s2, …).
 * @param {object[]} stations - station features (mutated)
 * @param {(feature: object) => boolean} isUserStation
 */
export function normalizeUserStationNamesInPlace(stations, isUserStation) {
  if (!Array.isArray(stations)) return;
  const used = collectUsedDefaultStationLabelNumbers(stations, isUserStation);

  for (const f of stations) {
    if (typeof isUserStation === "function" && !isUserStation(f)) continue;
    const props = f?.properties;
    const sid = props?.station_id;
    if (!props || typeof sid !== "string") continue;

    const labelFromName = parseDefaultStationLabelFromName(props.name);
    if (labelFromName != null && !isLegacyStationName(props.name, sid)) {
      props.user_default_label = labelFromName;
      props.name = formatDefaultStationName(`s${labelFromName}`);
      used.add(labelFromName);
      continue;
    }

    if (typeof props.user_default_label === "number" && Number.isFinite(props.user_default_label)) {
      props.name = formatDefaultStationName(`s${props.user_default_label}`);
      used.add(props.user_default_label);
      continue;
    }

    if (!isLegacyStationName(props.name, sid)) continue;

    const labelNumber = firstAvailableLabelNumber(used);
    used.add(labelNumber);
    props.user_default_label = labelNumber;
    props.name = formatDefaultStationName(`s${labelNumber}`);
  }
}
