/** MapLibre GL JS adapter — same engine-neutral surface as Mapbox (MapLike API subset). */
export {
  addMapImage,
  addMapLayer,
  addOrUpdateGeoJsonSource,
  applyMapLanguage,
  easeToMapCamera,
  fitMapBounds,
  flyToMapCamera,
  getLayerFilter,
  getMapBearing,
  getMapCanvas,
  getMapCanvasContainer,
  getMapCenter,
  getMapPitch,
  getMapStyle,
  getMapZoom,
  hasLayer,
  isMapReady,
  jumpToMapCamera,
  mapOff,
  mapOn,
  mapOnce,
  moveMapLayer,
  panMapBy,
  projectMapPoint,
  queryRenderedFeatures,
  removeLayerIfExists,
  removeSourceIfExists,
  setGeoJsonSourceData,
  setLayerFilter,
  setMapCanvasCursor,
  setMapConfigProperty,
  setMapLayoutProperty,
  setMapPaintProperty,
  setMapZoomInteractionsEnabled,
  styleUsesMapboxSlots,
  unprojectMapPoint,
} from "./mapAdapter.js";

/** @typedef {import('./mapTypes.js').MapLike} MapLike */
